In [1]:
import numpy as np

In [6]:
np.random.rand()

0.6827668845777966

In [26]:
index = np.arange(0, 512, int(1 / 0.25))
index_x, index_y = np.meshgrid(index, index)

In [39]:
index_x.shape

(128, 128)

In [37]:
index = np.arange(0, 3)
x_, y_ =  np.meshgrid(index, index)
x_.resize((1,x_.size))
y_.resize((1,x_.size))
print(np.concatenate((x_,y_), 0))

[[0 1 2 0 1 2 0 1 2]
 [0 0 0 1 1 1 2 2 2]]


In [14]:
import numpy as np
v = np.array([1,2,3,4,5,6,7,8])

In [17]:
v.reshape((4,2)).T[:, :2]

array([[1, 3],
       [2, 4]])

In [18]:
x = np.arange(512)
y = np.arange(512)
x, y = np.meshgrid(x, y)
x_lin = x.reshape((1, x.size))
y_lin = y.reshape((1, x.size))

In [19]:
x_lin

array([[  0,   1,   2, ..., 509, 510, 511]])

In [20]:
y_lin

array([[  0,   0,   0, ..., 511, 511, 511]])

In [25]:
y_lin.shape

(1, 262144)

In [21]:
coord_mat = np.concatenate((x_lin, y_lin), 0)

In [41]:
coord_mat[1,:].reshape(x.shape)

array([[  0,   0,   0, ...,   0,   0,   0],
       [  1,   1,   1, ...,   1,   1,   1],
       [  2,   2,   2, ...,   2,   2,   2],
       ...,
       [509, 509, 509, ..., 509, 509, 509],
       [510, 510, 510, ..., 510, 510, 510],
       [511, 511, 511, ..., 511, 511, 511]])

In [42]:
from torchvision.models import vgg16

In [43]:
vgg = vgg16()

In [ ]:
vgg.